# main menu (English)
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "team/"
weight = 2

[[main]]
name = "Results"
url = "results/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu (English)
[[footer]]
name = "Team"
url = "team/"
weight = 1

[[footer]]
name = "Projects"
url = "projects/"
weight = 2

[[footer]]
name = "Results"
url = "results/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4
